server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://database:5432/voting_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  task:
    scheduling:
      pool:
        size: 5
  kafka:
    bootstrap-servers: kafka:9092
    topic:
      resultado-votacao: resultado-votacao-topic
